server:
  port: 8881

spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/alaszcz/spring-cloud-config-repo
#               uri: file://d:/Dev/projects/spring-boot/spring-cloud-config-repo